# Generated by Django 3.1.5 on 2021-01-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('repository', models.CharField(default='dockerhub', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PortPod',
            fields=[
                ('pod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.pod')),
                ('container_id', models.CharField(max_length=2000)),
            ],
            bases=('delt.pod',),
        ),
        migrations.CreateModel(
            name='PortSettings',
            fields=[
                ('providersettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.providersettings')),
                ('allow_unsafe', models.BooleanField(default=False, help_text='Allow unsafe container (Doc)')),
                ('default_network', models.CharField(default='dev', max_length=100)),
            ],
            bases=('delt.providersettings',),
        ),
        migrations.CreateModel(
            name='ContainerTemplate',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.template')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.container')),
            ],
            bases=('delt.template',),
        ),
    ]
