# Generated by Django 2.2.12 on 2020-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowly',
            name='container_id',
            field=models.CharField(default='oisnoienoei', max_length=4000),
            preserve_default=False,
        ),
    ]
