# Generated by Django 3.1.3 on 2020-12-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0013_auto_20201210_1235'),
        ('port', '0002_container_containertemplate_portpod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flowly',
        ),
    ]
