# Generated by Django 3.1.3 on 2020-12-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0017_auto_20201210_1428'),
        ('port', '0003_delete_flowly'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortSettings',
            fields=[
                ('providersettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.providersettings')),
                ('allow_unsafe', models.BooleanField(default=False, help_text='Allow unsafe container (Doc)')),
            ],
            bases=('delt.providersettings',),
        ),
    ]
