# Generated by Django 2.2.12 on 2020-04-20 12:08

from django.db import migrations, models
import django.db.models.deletion
import fremmed.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendPod',
            fields=[
                ('pod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.Pod')),
                ('path', models.CharField(help_text='The Path this Frontend Node listenes to', max_length=1000, unique=True)),
                ('gate', models.CharField(default=uuid.UUID('6c72ec5d-3da4-407f-938c-ba5ae00771b3'), help_text='The Gate ID of this Pod', max_length=1000, unique=True)),
                ('access', fremmed.fields.AccessPolicy()),
            ],
            bases=('delt.pod',),
        ),
    ]
