# Generated by Django 3.1.3 on 2020-12-03 11:35

from django.db import migrations, models
import django.db.models.deletion
import fremmed.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendPod',
            fields=[
                ('pod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.pod')),
                ('gate', models.CharField(default=uuid.uuid4, help_text='The Gate ID of this Pod', max_length=1000, unique=True)),
                ('access', fremmed.fields.AccessPolicy(default=dict)),
            ],
            options={
                'permissions': (('access_pod', 'The user can host this Pod'),),
            },
            bases=('delt.pod',),
        ),
    ]
