# Generated by Django 2.2.12 on 2020-04-20 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fremmed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendpod',
            name='gate',
            field=models.CharField(default=uuid.UUID('961833c0-a538-4d22-957d-573492c029db'), help_text='The Gate ID of this Pod', max_length=1000, unique=True),
        ),
    ]
