# Generated by Django 2.2.12 on 2020-04-20 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fremmed', '0003_auto_20200420_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendpod',
            name='gate',
            field=models.CharField(default=uuid.uuid4, help_text='The Gate ID of this Pod', max_length=1000, unique=True),
        ),
    ]
