version: "3.4"

services:
  charles:
    image: postgres:12.2-alpine
    env_file:
      - arnheim.env

  frank:
    image: postgres:12.2-alpine
    env_file:
      - arnheim.env

  nathan:
    image: postgres:12.2-alpine
    env_file:
      - arnheim.env

  arbeider:
    build: .
    command: python /arbeider/manage.py runallworkers
    environment:
      - ARNHEIM_MODULES=test
    env_file:
      - arnheim.env
  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    command: server /export
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: weak_access_key
      MINIO_SECRET_KEY: weak_secret_key
    volumes:
        - mytest:/export
  redis:
    image: redis:latest
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: dev

volumes:
  mytest: