version: "3.4"

services:
  nathan:
    image: postgres:12.2-alpine
    env_file:
      - arnheim.env
  francesca:
    image: postgres:12.5-alpine
    env_file:
      - arnheim.env
  arbeider:
    build: .
    command: python /arbeider/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/arbeider:cached
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - ARNHEIM_MODULES=test
    env_file:
      - arnheim.env
  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    command: server /export
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: weak_access_key
      MINIO_SECRET_KEY: weak_secret_key
    volumes:
        - mytest:/export
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mister:
    image: jhnnsrs/mister:fancy
    hostname: localhost
    command: rabbitmq-server
    ports:
       - 5672:5672
       - 15672:15672

networks:
  default:
    external:
      name: dev

volumes:
  mytest: