version: "3.4"

services:
  arbeider:
    build: .
    command: python /arbeider/manage.py runallworkers
    environment:
      - ARNHEIM_MODULES=test
    env_file:
      - arnheim.env

networks:
  default:
    external:
      name: bergen_default