version: "3.4"

services:
  karl:
    image: postgres:12.2-alpine
    env_file:
      - arnheim.env
  frank:
    image: postgres:12.2-alpine
    env_file:
      - arnheim.env
  arbeider:
    build: .
    command: python /arbeider/manage.py runallworkers
    environment:
      - ARNHEIM_MODULES=test
    env_file:
      - arnheim.env

networks:
  default:
    external:
      name: bergen_default

volumes:
  newdata:
  oldfranceso: