# Generated by Django 3.1.3 on 2020-12-03 11:35

import delt.fields
import delt.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, help_text='A unique identifier of this Node on this Platform, calculated hashing the package and interface', max_length=1000, unique=True)),
                ('variety', models.CharField(help_text='Is this Node a Frontend, Backend, DaskExlusiv Node?', max_length=1000)),
                ('realm', models.CharField(help_text='The realm this Node was registered to?', max_length=1000)),
                ('package', models.CharField(help_text='The Package this Node belongs to', max_length=1000)),
                ('interface', models.CharField(help_text='The unique interface of this Node within the Package', max_length=1000)),
                ('publishers', delt.fields.PublishersField(default=dict, help_text='The publishers thie Node will send to')),
                ('name', models.CharField(help_text='The Package that channel belongs to', max_length=1000)),
                ('description', models.TextField(help_text='A Short description for the Node')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('inputs', delt.fields.InputsField(default=list)),
                ('outputs', delt.fields.OutputsField(default=list)),
                ('nodeclass', models.CharField(default='classic-node', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podclass', models.CharField(default='classic-pod', max_length=400)),
                ('status', models.CharField(default='pending', max_length=300)),
                ('provider', models.CharField(help_text='The provisioner that created this Pod', max_length=1000)),
                ('unique', models.UUIDField(default=uuid.uuid4, help_text='The Unique identifier of this POD', unique=True)),
                ('reference', models.CharField(blank=True, help_text='The Unique identifier of this POD', max_length=1000, null=True, unique=True)),
                ('persistent', models.BooleanField(default=False)),
                ('policy', models.CharField(default='*', max_length=5000)),
                ('node', models.ForeignKey(help_text='The node this Pod is an instance of', on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='delt.node')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This Providers Name', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this template', max_length=1000)),
                ('version', models.CharField(help_text='A short descriptor for the kind of version', max_length=400)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(help_text='The Node this Template Belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='delt.node')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delt.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, help_text='A unique identifier of this Route on this Platform, calculated hashing the package and interface', max_length=1000, unique=True)),
                ('url', models.URLField(help_text='The url to the Route', max_length=1000)),
                ('package', models.CharField(help_text='The Package this Node belongs to', max_length=1000)),
                ('provider', models.CharField(help_text='The Provider of this Route', max_length=1000)),
                ('interface', models.CharField(help_text='The unique interface of this Node within the Package', max_length=1000)),
                ('name', models.CharField(help_text='The Package that channel belongs to', max_length=1000)),
                ('description', models.TextField(help_text='A Short description for the Node')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='delt.node')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique identifier of this Repository on this Platform, calculated hashing the package and interface', max_length=1000)),
                ('type', models.CharField(help_text='What sort of repository is this', max_length=300)),
                ('creator', models.ForeignKey(blank=True, help_text='The Person that created this repository', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('provider', models.CharField(help_text='The Provider', max_length=1000)),
                ('subselector', models.CharField(help_text='The selector', max_length=1000)),
                ('token', models.CharField(blank=True, default=uuid.UUID('38251b2b-17ac-445a-a619-daf26a1c3753'), help_text='The Token that created this Provision', max_length=1000)),
                ('reference', models.CharField(default=uuid.uuid4, help_text='The Unique identifier of this Provision', max_length=1000, unique=True)),
                ('status', models.CharField(blank=True, help_text='This provisions status', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(help_text='The node this provision connects', on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='delt.node')),
                ('parent', models.ForeignKey(blank=True, help_text='The Provisions parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='delt.provision')),
                ('pod', models.ForeignKey(blank=True, help_text='The pod this provision connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='delt.pod')),
                ('template', models.ForeignKey(blank=True, help_text='The template used to create this provision', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='delt.template')),
                ('user', models.ForeignKey(help_text='This provision creator', max_length=1000, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pod',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template used to create this pod', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='delt.template'),
        ),
        migrations.AddField(
            model_name='node',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delt.repository'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', delt.fields.InputsField(blank=True, help_text='The Inputs', null=True)),
                ('outputs', delt.fields.OutputsField(blank=True, help_text='The Outputs', null=True)),
                ('settings', delt.fields.SettingsField(default=delt.helpers.get_default_job_settings, max_length=1000)),
                ('status', models.CharField(default='pending', max_length=500)),
                ('reference', models.CharField(default=uuid.uuid4, help_text='The Nodeinstance this Job lives on', max_length=400)),
                ('selector', delt.fields.SelectorField(blank=True, help_text='The Selectivity for Instances of this Node (especially unique Frontends)', max_length=400)),
                ('unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pod', models.ForeignKey(blank=True, help_text='The Pod this Job lives on', null=True, on_delete=django.db.models.deletion.CASCADE, to='delt.pod')),
            ],
            options={
                'permissions': (('queue_job', 'Queue Job'),),
            },
        ),
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', delt.fields.InputsField(blank=True, help_text='The Inputs', null=True)),
                ('outputs', delt.fields.OutputsField(blank=True, help_text='The Outputs', null=True)),
                ('reference', models.CharField(default=uuid.uuid4, help_text='The Unique identifier of this Provision', max_length=1000, unique=True)),
                ('status', models.CharField(help_text='This provisions status', max_length=1000)),
                ('token', models.CharField(blank=True, default=uuid.UUID('f6d846d5-8e7c-4678-a5e0-4f224c849378'), help_text='The Token that created this Provision', max_length=1000, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pod', models.ForeignKey(help_text='The pod this provision connects', on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='delt.pod')),
            ],
        ),
    ]
