# Generated by Django 2.2.12 on 2020-04-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod',
            old_name='persistant',
            new_name='persistent',
        ),
    ]
