# Generated by Django 2.2.14 on 2020-07-13 14:39

import delt.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignation',
            name='outputs',
            field=delt.fields.OutputsField(blank=True, help_text='The Outputs', null=True),
        ),
    ]
