# Generated by Django 3.1.5 on 2021-01-29 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('3c68a39c-8cde-46a0-bc0c-073ea45e46f5'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('91680ad8-d6c3-49dd-805c-77495d221650'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
