# Generated by Django 2.2.12 on 2020-04-17 10:56

import delt.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='selector',
            field=delt.fields.SelectorField(default=uuid.uuid4, help_text='The Selectivity for Instances of this Node (especially unique Frontends)', max_length=400),
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provisioner', models.CharField(help_text='The provisioner that created this Pod', max_length=1000)),
                ('policy', delt.fields.AccessPolicy(help_text='The access policy attached to this pod')),
                ('node', models.ForeignKey(help_text='The node this Pod is an instance of', on_delete=django.db.models.deletion.CASCADE, to='delt.Node')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='pod',
            field=models.ForeignKey(blank=True, help_text='The Pod this Job lives on', null=True, on_delete=django.db.models.deletion.CASCADE, to='delt.Pod'),
        ),
    ]
