# Generated by Django 3.1.3 on 2020-12-14 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0002_auto_20201214_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='host',
            field=models.CharField(default='localhost', help_text='Where are we storing this??', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('6c33d43c-1432-4c4c-94df-b2984fb161e2'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f89f8b3e-e2b9-449a-90b6-b116cbb3136c'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
