# Generated by Django 3.1.3 on 2020-12-03 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0002_auto_20201203_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('01103665-9792-4917-aec1-5b06a3c0dcb0'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('e828ffe7-4589-4049-bf08-87350aced4e5'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
