# Generated by Django 3.1.5 on 2021-01-29 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0002_auto_20210129_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('69bab656-b18d-48d1-9156-aed00d21fa58'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('ebdfffa6-7831-4d92-9f85-7f41521382fe'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
