# Generated by Django 2.2.12 on 2020-04-17 13:23

import delt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0002_auto_20200417_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='selector',
            field=delt.fields.SelectorField(blank=True, help_text='The Selectivity for Instances of this Node (especially unique Frontends)', max_length=400),
        ),
    ]
