# Generated by Django 2.2.12 on 2020-04-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0003_auto_20200420_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='node',
            field=models.ForeignKey(help_text='The node this Pod is an instance of', on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='delt.Node'),
        ),
    ]
