# Generated by Django 3.1.5 on 2021-01-29 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0003_auto_20210129_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('c6338fee-921f-4e22-bc41-56c037a29063'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('a12edf90-1f30-4d30-b848-e4039f560af9'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
