# Generated by Django 2.2.14 on 2020-07-21 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0003_auto_20200721_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('8e30fa9c-ff3e-4de9-9b29-f9d4435501c5'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('41945119-b25f-4e85-8914-d83b89f28ab3'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
