# Generated by Django 3.1.3 on 2020-12-03 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0003_auto_20201203_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('dc318274-cd18-4e65-a91b-2ff6b477c5ce'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('a53c9b80-7288-4fa7-8470-d15b3699863b'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
