# Generated by Django 3.1.3 on 2020-12-14 09:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0003_auto_20201214_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delt.datapoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('a8d4992b-a0d7-42d1-8def-e6f52eaf3334'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='name',
            field=models.CharField(help_text='A unique identifier for this datapoint, will be prepeneded to the Model it hosts', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('52e45403-c1fd-4328-9e9f-87721723fc8d'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
