# Generated by Django 2.2.12 on 2020-04-21 13:13

import delt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0004_auto_20200420_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='publishers',
            field=delt.fields.PublishersField(default=list, help_text='The publishers thie Node will send to'),
        ),
    ]
