# Generated by Django 3.1.5 on 2021-01-29 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0004_auto_20210129_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('9ee39439-e5bb-4b08-95e3-4583198f1878'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('7693a613-9094-4f65-a24d-3b49f22c0078'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
