# Generated by Django 2.2.14 on 2020-07-23 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0004_auto_20200721_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('aea005f0-5ad3-4552-83d8-1f209258eaf5'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f98f0ba6-f261-4ae6-a90b-fdae7a5c4133'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
