# Generated by Django 3.1.3 on 2020-12-04 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0004_auto_20201203_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='message',
            field=models.CharField(default='nothing', help_text='This provisions status', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('62f47a21-eb6e-4e0e-adec-1a0181662f4d'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('33b1c80c-80e7-4515-8954-c0ec0855447b'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
