# Generated by Django 3.1.5 on 2021-01-29 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0005_auto_20210129_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('42c5bc03-32aa-471d-b963-c3470a5bf8dd'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('bb6bd50a-1e8b-4571-8eae-30281c93c33d'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
