# Generated by Django 3.1.3 on 2020-12-16 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0005_auto_20201214_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1910b1fc-961f-4c5e-bab7-381dca78d3ec'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='node',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='delt.repository'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('6ac07559-4d38-4c6a-a21c-5361f751ad84'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='selector',
            name='provider',
            field=models.ForeignKey(help_text='The provider these kwargs belong to', on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='delt.provider'),
        ),
    ]
