# Generated by Django 2.2.14 on 2020-07-23 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0005_auto_20200723_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('3302a0b5-0821-4406-9269-68895b2c54eb'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('049b3b77-d9bd-4130-b517-ff69af5fa421'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
