# Generated by Django 3.1.3 on 2020-12-04 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0005_auto_20201204_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('062bc2c2-d374-4fe1-961b-376b334e4544'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('47611f61-dafd-4cd9-8033-8218d64758fc'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
