# Generated by Django 2.2.14 on 2020-09-08 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0006_auto_20200723_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('a78cb7f0-90d7-433e-8a51-22b7e3c39332'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('c1b607e2-1ea2-4875-92f0-84a08437a1eb'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
