# Generated by Django 3.1.3 on 2020-12-16 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0006_auto_20201216_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1d27c098-abce-4dca-9e09-daed308598ac'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('5b13f27e-8140-4bec-8ba0-6a1cdbff41e7'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
