# Generated by Django 3.1.5 on 2021-01-29 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0006_auto_20210129_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1f678ec4-a11d-4938-ba67-3794dd7b5c15'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f16e7cf8-6849-4962-8d15-8da4601ece06'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
