# Generated by Django 3.1.3 on 2020-12-04 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0006_auto_20201204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('c0c21376-6a73-4a7e-ba21-8f70f28e6b40'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('dc20b299-59be-4641-a998-3f9010f3f6d4'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
