# Generated by Django 3.1.3 on 2020-12-16 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0007_auto_20201216_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1fe522e8-e922-403d-9212-a145a5444c56'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('b9e5af9a-ad0e-4d7b-80ed-8c4c9de305e4'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
