# Generated by Django 3.1.3 on 2020-12-10 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0007_auto_20201204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('0c0b3a2e-e6cd-409f-8ff7-334b6b565ed6'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('bdca27aa-3dc7-4b9f-b1e2-0bb606917ad0'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
