# Generated by Django 3.1.3 on 2020-12-10 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0008_auto_20201210_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('4a830cb7-5ab1-4605-b5a7-7b4104940830'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('b827caa3-ca91-4c5f-b490-b58a5fbf8fa1'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
