# Generated by Django 3.1.3 on 2020-12-16 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0008_auto_20201216_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('068e227e-24a6-499d-9279-263bfcba288b'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('46ba0f90-c9df-4ecb-939a-5756e0276e39'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
