# Generated by Django 3.1.3 on 2020-12-16 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0009_auto_20201216_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('c4df4c37-2708-471f-874a-c60c4cbf08d5'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('44a75e1e-858a-41b1-99f2-033da5434f97'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
