# Generated by Django 2.2.14 on 2020-09-21 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0009_auto_20200917_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('134029ed-49b7-40bc-b68d-f18b1c36c7b2'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('62eb36e9-3537-4d4c-bc53-22bd50f8a0e7'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
