# Generated by Django 3.1.3 on 2020-12-10 12:31

import delt.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0009_auto_20201210_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('7432f481-588e-4be9-90ba-f790ebdfbef3'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('5b20bfbd-4009-4bcf-a423-9ffa7475549f'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(default=delt.utils.generate_random_name, help_text='The name of this template', max_length=1000),
        ),
    ]
