# Generated by Django 2.2.14 on 2020-09-21 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0010_auto_20200921_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('0c8f0b61-48a5-4883-8d17-978fee75db25'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('99d2226e-3ed4-4e29-beb6-ca3b9e787ec1'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
