# Generated by Django 3.1.3 on 2021-01-04 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0010_auto_20201216_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1f19e19d-fa45-42dd-b0ac-66f6cd196c13'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('8ac79cce-fd32-4952-9620-8f7690f1b4f6'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
