# Generated by Django 3.1.3 on 2020-12-10 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0010_auto_20201210_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('5dfcf6b5-de94-4ba4-b091-33df2cdb87ca'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('fddce24e-22f2-41ac-ba56-f72a031570b9'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
