# Generated by Django 3.1.3 on 2020-12-10 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0011_auto_20201210_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('4b1e0cd7-2dd3-4d64-b2b2-4cc3f8949f9a'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('ac0e29c8-c7d5-40ff-a798-e27ccf5c1c3e'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
