# Generated by Django 2.2.14 on 2020-09-21 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0011_auto_20200921_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('ecf5ad07-3620-4ede-99da-0bc77b722824'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('96a641e3-29f7-49f6-ba29-891e40e0d21b'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
