# Generated by Django 3.1.3 on 2021-01-04 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0011_auto_20210104_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('2679df9c-c23b-4251-804a-72d32d1b53e8'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('5d88f43b-8dc5-481e-821c-e05ef2d8c90f'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
