# Generated by Django 2.2.14 on 2020-09-21 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0012_auto_20200921_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('4d98e0ea-1483-4d3c-b333-5953c9d1f727'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('a8904699-6656-41c5-8e4b-39954ba7f431'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
