# Generated by Django 3.1.3 on 2020-12-10 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0012_auto_20201210_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('781b6d32-f719-466e-9d73-e7ed8016d153'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('c14241e9-8209-4f79-b81f-7d359a485eb2'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
