# Generated by Django 3.1.3 on 2021-01-04 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0012_auto_20210104_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='inward',
            field=models.CharField(default='arbeider', help_text='The Microservice way', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('e13be7f5-078e-490c-954a-2440c17dd95e'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1da805ea-c891-4cf1-b794-ee277558e1a9'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
