# Generated by Django 3.1.3 on 2021-01-04 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0013_auto_20210104_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('011f3645-8452-4bab-b28d-62556f471a5c'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('268cf0a3-59d9-4181-9fef-b17e63f96f19'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
