# Generated by Django 2.2.14 on 2020-09-21 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0013_auto_20200921_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='policy',
            field=models.CharField(default='*', max_length=5000),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('16cef15d-a516-4354-b250-19f6940d4c48'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('d66e62a7-3d61-416c-b68f-66c5d7735e0c'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
