# Generated by Django 3.1.3 on 2020-12-10 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0013_auto_20201210_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='installed_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('99be901d-effd-4054-b923-fc7356e1658d'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('7e02347d-1b77-4d74-85e0-daf9a9486abf'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('active', models.BooleanField(default=True, help_text='Is this provider active or no longer active?')),
                ('provider', models.ForeignKey(help_text='The implemented Provider!', on_delete=django.db.models.deletion.CASCADE, to='delt.provider')),
            ],
        ),
    ]
