# Generated by Django 3.1.3 on 2020-12-10 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0014_auto_20201210_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('bcc65b32-4bcb-48a4-b04e-780930cbee5f'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('df63d8b7-8d5c-4987-8f63-66e839504dae'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
