# Generated by Django 3.1.3 on 2020-12-10 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0015_auto_20201210_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('6d99d8f8-a6b5-4cf4-93cb-f8ca33bd85c0'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('4773e090-e0ee-4e86-94dd-3089f5397d71'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
