# Generated by Django 2.2.16 on 2020-09-29 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0016_auto_20200925_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f6ffa288-e2fb-4efc-b596-708459361278'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f69af00b-7e96-4aad-950f-c13985175a20'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
