# Generated by Django 3.1.3 on 2020-12-10 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0016_auto_20201210_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('8012d428-09b3-488e-b629-858b698f6f24'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('249fbbc5-cf63-40f6-89fd-5792d763aaeb'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
