# Generated by Django 3.1.3 on 2020-12-10 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0017_auto_20201210_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('fc20011a-8156-4eb0-b986-58a0ffdcd2fd'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('d15a24df-4c63-4e9c-91fb-0c41c5939b13'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
