# Generated by Django 3.1.1 on 2020-09-30 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0017_auto_20200929_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('9d17bc44-c5b4-4651-bfdb-274768f0b142'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('0926e67d-5e1d-4b2a-a7fe-2457a621e526'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
