# Generated by Django 3.1.3 on 2020-12-10 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0018_auto_20201210_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('ca838cb0-b307-4aa3-83d7-b55d9e6b399c'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('5bddd687-67c8-4327-9159-84492cc9453e'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
