# Generated by Django 3.1.1 on 2020-09-30 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0018_auto_20200930_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('aed4f81b-a139-4ed3-ad05-a789f80b6da9'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('22f68c3e-8cda-4377-9561-19925f765c72'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
