# Generated by Django 3.1.3 on 2020-12-10 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0019_auto_20201210_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1f8252f9-063e-45ce-9c35-9308caa3c7bc'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('8ac18f63-ba61-434f-a32f-876dcf2a6a15'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
