# Generated by Django 3.1.1 on 2020-09-30 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0019_auto_20200930_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('6bcc1357-ceb4-4423-8e13-1bc93e24e61f'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('64b7810b-9d8c-4cfc-a69a-60177ab7c123'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Flow',
        ),
    ]
