# Generated by Django 3.1.2 on 2020-10-08 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0020_auto_20200930_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('509f71cd-4423-46e8-88bb-a23603ce9549'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f73b6ea8-34a0-4cc4-83a5-d33c3da566e3'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this template', max_length=1000)),
                ('node', models.ForeignKey(help_text='The Node this Template Belongs to', on_delete=django.db.models.deletion.CASCADE, to='delt.node')),
            ],
        ),
    ]
