# Generated by Django 3.1.2 on 2020-10-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delt', '0021_auto_20201008_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('bafc92b1-b078-4db9-a67d-5d770ea8e68c'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('961b93c7-b514-4b28-a02c-eadb28089333'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
