# Generated by Django 3.1.3 on 2020-12-10 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0021_auto_20201210_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('759ba787-af10-446e-8a2c-d9a256d6ba89'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f0472b00-bd48-48d3-b39e-03103c6ec343'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
