# Generated by Django 3.1.3 on 2020-12-10 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0022_auto_20201210_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('438ad99e-151a-461d-8f96-e1dc3d64ecdc'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('a1390535-9872-413d-83bc-22efae5523b8'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
