# Generated by Django 3.1.2 on 2020-10-08 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delt', '0022_auto_20201008_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The Person that created this repository', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('254bf50f-a62c-43be-b095-1560e858e07e'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('e55a0309-3bb1-4983-a538-0a23e57c002f'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
