# Generated by Django 3.1.2 on 2020-10-08 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0023_auto_20201008_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('b65f4bfe-8acb-42bf-8ffd-7e3b265e4a43'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('9cc01e82-c21f-4c4e-b51e-539935944919'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(help_text='A unique identifier of this Repository on this Platform, calculated hashing the package and interface', max_length=1000),
        ),
    ]
