# Generated by Django 3.1.3 on 2020-12-10 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0023_auto_20201210_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('344ece06-e421-489b-b2a1-9ae517fb4c4f'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('551a4419-f844-4d36-880c-7434a9249e7f'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
