# Generated by Django 3.1.2 on 2020-10-13 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0024_auto_20201008_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('df4b3c33-12d6-4a34-b84c-58e9b15bc416'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('70375b9a-e639-4afb-b7c5-6170af5b7297'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
