# Generated by Django 3.1.2 on 2020-10-14 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0025_auto_20201013_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='type',
            field=models.CharField(default='default', help_text='What sort of repository is this', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('57918359-1c94-453e-94e4-3de6e3b9ce93'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('89ca5dae-e3d8-4587-b32f-0b3d0470f130'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
