# Generated by Django 3.1.2 on 2020-10-14 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0026_auto_20201014_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template used to create this provision', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='delt.template'),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('1fcfab8e-85ad-4955-8674-6f53af829f97'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('882f5528-0ba9-4bf8-aa77-dd21eaa43116'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
