# Generated by Django 3.1.2 on 2020-10-14 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0027_auto_20201014_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template used to create this pod', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='delt.template'),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('3e50aa5a-291f-4ca1-a82d-79be2d9b35d5'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('10278118-aa3e-43e2-9bfe-121217b92f40'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
