# Generated by Django 3.1.2 on 2020-10-15 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0028_auto_20201014_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This Providers Name', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('0d3be64a-026d-4e42-9cf0-2362c20d1229'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('e2f67907-b97a-4598-8dde-c6ec68104c56'), help_text='The Token that created this Provision', max_length=1000),
        ),
        migrations.AlterField(
            model_name='template',
            name='node',
            field=models.ForeignKey(help_text='The Node this Template Belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='delt.node'),
        ),
        migrations.AddField(
            model_name='template',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delt.provider'),
        ),
    ]
