# Generated by Django 3.1.3 on 2020-11-19 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0030_auto_20201113_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('3af3cae7-0d0c-4759-906c-805fbcac44b9'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('a3872be7-dd14-4366-8f3d-008a46581693'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
