# Generated by Django 3.1.3 on 2020-11-19 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0031_auto_20201119_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('98166205-498d-45c2-bd63-2110b83c351d'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('4818a241-8b94-4f38-807a-43bb0d17b86d'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
