# Generated by Django 3.1.3 on 2020-12-01 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0033_auto_20201119_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('540cf308-f67d-4bc9-b9c2-c47f0376b518'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('949d9352-b77e-4d40-83e4-4108c945c2d1'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
