# Generated by Django 3.1.3 on 2020-12-01 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0034_auto_20201201_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('49c1059c-0d1f-4381-a29f-937766863f44'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('2e641f8a-55c5-4cb5-a9e2-b61df7ba0855'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
