# Generated by Django 3.1.3 on 2020-12-02 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0035_auto_20201201_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('34b34ecc-7b8a-492b-9571-429b1a441bfb'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('3aae72fb-1b35-4c7a-9af9-a684067e3d41'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
