# Generated by Django 3.1.3 on 2020-12-02 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0036_auto_20201202_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('c65d2138-138b-41d7-b44c-cc8d243e130d'), help_text='The Token that created this Provision', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('3e0f08c7-dec8-45b2-936b-a69a716f2aba'), help_text='The Token that created this Provision', max_length=1000),
        ),
    ]
