# Generated by Django 3.1.5 on 2021-01-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineRoi',
            fields=[
                ('roi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.roi')),
                ('length', models.FloatField()),
            ],
            bases=('elements.roi',),
        ),
    ]
