# Generated by Django 3.1.3 on 2020-12-10 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0004_auto_20201210_1231'),
        ('port', '0002_container_containertemplate_portpod'),
    ]

    operations = [
        migrations.CreateModel(
            name='RxCompiler',
            fields=[
                ('compiler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flow.compiler')),
            ],
            bases=('flow.compiler',),
        ),
        migrations.CreateModel(
            name='RxGraph',
            fields=[
                ('executiongraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flow.executiongraph')),
                ('value', models.JSONField()),
            ],
            bases=('flow.executiongraph',),
        ),
        migrations.CreateModel(
            name='RxPod',
            fields=[
                ('portpod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='port.portpod')),
            ],
            bases=('port.portpod',),
        ),
        migrations.CreateModel(
            name='RxTemplate',
            fields=[
                ('containertemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='port.containertemplate')),
                ('active', models.BooleanField(default=False, help_text='Is this volunteer active right now')),
                ('identifier', models.UUIDField(default=uuid.uuid4, help_text='The identifier for this volunteer')),
                ('graph', models.ForeignKey(help_text='The RxGraph atached to this Container', on_delete=django.db.models.deletion.CASCADE, to='reactive.rxgraph')),
            ],
            bases=('port.containertemplate',),
        ),
    ]
