# Generated by Django 3.1.3 on 2020-12-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_delete_flowly'),
        ('delt', '0015_auto_20201210_1307'),
        ('reactive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RxSettings',
            fields=[
                ('providersettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.providersettings')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.container')),
            ],
            bases=('delt.providersettings',),
        ),
    ]
