# Generated by Django 3.1.3 on 2020-12-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_portsettings'),
        ('reactive', '0002_rxsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rxsettings',
            name='providersettings_ptr',
        ),
        migrations.AddField(
            model_name='rxsettings',
            name='portsettings_ptr',
            field=models.OneToOneField(auto_created=True, default=32, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='port.portsettings'),
            preserve_default=False,
        ),
    ]
