# Generated by Django 3.1.3 on 2020-12-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactive', '0003_auto_20201210_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rxtemplate',
            name='active',
        ),
        migrations.AlterField(
            model_name='rxtemplate',
            name='graph',
            field=models.ForeignKey(help_text='The RxGraph atached to this potential Worker', on_delete=django.db.models.deletion.CASCADE, to='reactive.rxgraph'),
        ),
    ]
