# Generated by Django 3.1.2 on 2020-10-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0027_auto_20201014_1405'),
        ('kanal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanalTemplate',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.template')),
                ('channel', models.CharField(help_text='The channel the implemtation lives on', max_length=1000, unique=True)),
            ],
            bases=('delt.template',),
        ),
    ]
