# Generated by Django 3.1.5 on 2021-01-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalderRoute',
            fields=[
                ('route_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.route')),
                ('operation_name', models.CharField(help_text='The Operation name of this endpoint', max_length=1000)),
            ],
            bases=('delt.route',),
        ),
    ]
