# Generated by Django 3.1.3 on 2020-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balderroute',
            name='operation_name',
            field=models.CharField(default='void', help_text='The Operation name of this endpoint', max_length=1000),
            preserve_default=False,
        ),
    ]
