# Generated by Django 3.1.3 on 2020-12-03 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.template')),
                ('active', models.BooleanField(default=False, help_text='Is this volunteer active right now')),
                ('identifier', models.UUIDField(default=uuid.uuid4, help_text='The identifier for this volunteer')),
            ],
            bases=('delt.template',),
        ),
        migrations.CreateModel(
            name='VartPod',
            fields=[
                ('pod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.pod')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vart.volunteer')),
            ],
            bases=('delt.pod',),
        ),
    ]
