# Generated by Django 3.1.3 on 2020-12-01 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delt', '0034_auto_20201201_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, help_text='The identifier for this volunteer')),
                ('node', models.ForeignKey(help_text='The volunteers node', on_delete=django.db.models.deletion.CASCADE, to='delt.node')),
            ],
        ),
    ]
