# Generated by Django 3.1.3 on 2020-12-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0016_auto_20201210_1336'),
        ('vart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VartSettings',
            fields=[
                ('providersettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.providersettings')),
                ('allow_public', models.BooleanField(default=False, help_text='Allow Public Clients?')),
            ],
            bases=('delt.providersettings',),
        ),
    ]
