# Generated by Django 3.1.3 on 2020-12-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0035_auto_20201201_1318'),
        ('vart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this volunteer active right now'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VartPod',
            fields=[
                ('pod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.pod')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vart.volunteer')),
            ],
            bases=('delt.pod',),
        ),
    ]
