# Generated by Django 3.1.3 on 2020-12-02 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vart', '0002_auto_20201201_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this volunteer active right now'),
        ),
    ]
