# Generated by Django 3.1.5 on 2021-01-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peasentpod',
            name='peasent',
        ),
    ]
