# Generated by Django 2.2.12 on 2020-04-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.Node')),
            ],
            bases=('delt.node',),
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.Job')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Tester')),
            ],
            bases=('delt.job',),
        ),
    ]
