# Generated by Django 3.1.3 on 2020-12-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='The channel this template will publish to!', max_length=1000)),
                ('slack_bot_token', models.CharField(help_text='The Help token for slack', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SlackoPublisher',
            fields=[
                ('pod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.pod')),
            ],
            bases=('delt.pod',),
        ),
        migrations.CreateModel(
            name='SlackoSettings',
            fields=[
                ('providersettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.providersettings')),
                ('default_workspace', models.CharField(help_text='The Default Workspace you want to publish to', max_length=1000)),
                ('app_id', models.CharField(help_text='The App_id in Slack', max_length=400)),
                ('client_id', models.CharField(help_text='The SlackAPP Oauth2 Client ID', max_length=1000)),
                ('client_secret', models.CharField(help_text='The SlackAPP Oauth2 Client Secret', max_length=1000)),
                ('signing_secret', models.CharField(help_text='The SlackAPP Oauth2 Client Signing Secret (used to verify authenticity of slack)', max_length=1000)),
            ],
            bases=('delt.providersettings',),
        ),
        migrations.CreateModel(
            name='SlackoPublisherTemplate',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.template')),
                ('channel', models.ForeignKey(help_text='The channel we will use', on_delete=django.db.models.deletion.CASCADE, to='slacko.slackchannel')),
            ],
            bases=('delt.template',),
        ),
    ]
