# Generated by Django 3.1.5 on 2021-01-29 11:53

import delt.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilerRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='validate', max_length=100)),
                ('operation_name', models.CharField(default='void', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=delt.utils.generate_random_name, max_length=1000)),
                ('version', models.CharField(default='standard', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0alpha', max_length=100)),
                ('name', models.CharField(default=delt.utils.generate_random_name, max_length=100, null=True)),
                ('diagram', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='Add a Description', max_length=50000, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delt.node')),
            ],
        ),
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=delt.utils.generate_random_name, max_length=1000)),
                ('validation_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.compilerroute')),
            ],
        ),
    ]
