# Generated by Django 3.1.3 on 2020-12-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0006_auto_20201216_1507'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='template_ptr',
        ),
        migrations.RemoveField(
            model_name='flownode',
            name='node_ptr',
        ),
        migrations.AddField(
            model_name='graph',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
        migrations.DeleteModel(
            name='Flow',
        ),
        migrations.DeleteModel(
            name='FlowNode',
        ),
    ]
