# Generated by Django 3.1.1 on 2020-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='diagram',
            field=models.JSONField(),
        ),
    ]
