# Generated by Django 3.1.3 on 2020-12-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flownode',
            name='graph',
        ),
    ]
