# Generated by Django 3.1.2 on 2020-10-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0022_auto_20201008_1153'),
        ('flow', '0002_auto_20200930_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delt.template')),
                ('diagram', models.JSONField()),
            ],
            bases=('delt.template',),
        ),
        migrations.RemoveField(
            model_name='graph',
            name='creator',
        ),
    ]
