# Generated by Django 3.1.3 on 2020-12-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0009_auto_20201210_1011'),
        ('flow', '0002_remove_flownode_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delt.node'),
        ),
    ]
