# Generated by Django 2.2.12 on 2020-06-01 14:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_remove_graph_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='diagram',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
