# Generated by Django 3.1.3 on 2020-12-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20201216_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='compiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.compiler'),
        ),
    ]
