# Generated by Django 3.1.3 on 2020-12-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_graph_compiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='compiler',
        ),
    ]
