# Generated by Django 3.1.3 on 2020-12-10 12:31

import delt.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delt', '0010_auto_20201210_1231'),
        ('flow', '0003_graph_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=delt.utils.generate_random_name, max_length=1000)),
                ('version', models.CharField(default='standard', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(default=delt.utils.generate_random_name, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=delt.utils.generate_random_name, max_length=1000)),
                ('validation_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delt.route')),
            ],
        ),
    ]
