# Generated by Django 3.1.3 on 2020-12-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20201210_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilerRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='validate', max_length=100)),
                ('operation_name', models.CharField(default='void', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='compiler',
            name='validation_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.compilerroute'),
        ),
    ]
