# Generated by Django 3.1.3 on 2020-12-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_remove_graph_compiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='group',
        ),
        migrations.AlterField(
            model_name='graph',
            name='description',
            field=models.CharField(blank=True, default='Add a Description', max_length=50000, null=True),
        ),
    ]
