# Generated by Django 3.1.3 on 2020-12-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_auto_20201216_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='diagram',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
