# Generated by Django 3.1.3 on 2020-12-04 15:32

from django.db import migrations, models
import matrise.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='shape',
            field=matrise.fields.ShapeField(base_field=models.IntegerField(), blank=True, help_text='The arrays shape', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='shape',
            field=matrise.fields.ShapeField(base_field=models.IntegerField(), blank=True, help_text='The arrays shape', null=True, size=None),
        ),
    ]
