# Generated by Django 3.1.3 on 2021-01-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='creator',
        ),
    ]
