# Generated by Django 3.1.3 on 2021-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_remove_representation_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='has_array',
            field=models.BooleanField(default=False, help_text='Does this Model have attached Data?', verbose_name='has_array'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='has_array',
            field=models.BooleanField(default=False, help_text='Does this Model have attached Data?', verbose_name='has_array'),
        ),
    ]
