# Generated by Django 3.1.3 on 2020-12-04 15:32

from django.db import migrations, models
import matrise.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20201204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='dims',
            field=matrise.fields.DimsField(base_field=models.CharField(max_length=100), blank=True, help_text='The arrays dimension', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='dims',
            field=matrise.fields.DimsField(base_field=models.CharField(max_length=100), blank=True, help_text='The arrays dimension', null=True, size=None),
        ),
    ]
