# Generated by Django 2.2.16 on 2020-09-25 14:59

from django.db import migrations
import matrise.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_representation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='channels',
            field=matrise.mixins.ChannelsField(blank=True, null=True),
        ),
    ]
