# Generated by Django 2.2.16 on 2020-09-29 13:32

from django.db import migrations
import matrise.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_representation_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='planes',
            field=matrise.mixins.PlanesField(blank=True, null=True),
        ),
    ]
